In [1]:
##Broadcasting

In [2]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
#Two lines of Python code will calculate calories and precentage of those

#Start with calories
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
#Calculate percentages
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [7]:
#Calculate percentages omitting reshape
#Example of broadcasting
percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


Tips and tricks to avoid errors

In [8]:
a = np.random.randn(5)

In [9]:
print(a)

[-0.38603193 -0.25072931 -1.47612066 -0.28004732 -0.87740746]


In [10]:
print(a.shape)

(5,)


In [11]:
print(a.T)

[-0.38603193 -0.25072931 -1.47612066 -0.28004732 -0.87740746]


In [12]:
print(np.dot(a,a.T))

3.2390883923836644


In [14]:
a = np.random.rand(5,1)
print(a)

[[0.24283391]
 [0.05780585]
 [0.88236044]
 [0.42597705]
 [0.64575552]]


In [15]:
print(a.T)

[[0.24283391 0.05780585 0.88236044 0.42597705 0.64575552]]


In [17]:
#Note [[ for matrix instead of [ for array 

In [19]:
print(np.dot(a,a.T))

[[0.05896831 0.01403722 0.21426703 0.10344167 0.15681133]
 [0.01403722 0.00334152 0.05100559 0.02462396 0.03732844]
 [0.21426703 0.05100559 0.77855994 0.3758653  0.56978912]
 [0.10344167 0.02462396 0.3758653  0.18145645 0.27507703]
 [0.15681133 0.03732844 0.56978912 0.27507703 0.41700019]]
